[package]
name = "groupby"
version = "0.1.0"
authors = ["J/A <archer884@gmail.com>"]

[dependencies]

[dev-dependencies]
criterion = "*"
fnv = "*"
fxhash = "*"
metrohash = "*"

[[bench]]
name = "hash_performance"
harness = false
